import { Injectable, Inject, Logger } from '@nestjs/common';
import { QueryArrayConfig, QueryArrayResult, Pool } from "pg";
import { ApiProperty } from '@nestjs/swagger';

@Injectable()
export class AppService {
  private readonly logger = new Logger(AppService.name)
  constructor(@Inject('DATABASE_POOL') private readonly pool: Pool) {}

  async getResult(userId: string): Promise<GetResultRow> {
    const client = await this.pool.connect();
    try {
      const result = await getResult(client, { userId });
      this.logger.log(result);
      return result;
    } finally {
      client.release();
    }
  }

  async submitResult(userId: string, body: SubmitArgs): Promise<SubmitRow> {
    const client = await this.pool.connect();
    try {
      this.logger.log(body);
      const result = await submit(client,  body);
      return result;
    } finally {
      client.release();
    }
  }
}

// Code below is copied from db/db/query_sql.ts, there are not handcoded but generated by sqlc
// Why not import from db/db/query_sql.ts? Because i'm not sure how to rightly structure the generated code into the nestjs project
interface Client {
    query: (config: QueryArrayConfig) => Promise<QueryArrayResult>;
}

// -------------------------------------------------------------------------------section for GetResult start
const getResultQuery = `-- name: GetResult :one
SELECT
        user_id,
        full_name,
        final_result,
        p.personality_role_name,
        p.cluster,
        outgoing,
        solitary,
        conceptual,
        practical,
        empathetic,
        logical,
        organized,
        flexible
    FROM talent_mapping.view_final_result v
        left join talent_mapping.personality_roles p on v.final_result = p.typology
    WHERE user_id =$1 LIMIT 1`;

interface GetResultArgs {
    userId: string;
}

export interface GetResultRow {
    userId: string;
    fullName: string;
    finalResult: string;
    personalityRoleName: string | null;
    cluster: string | null;
    outgoing: number;
    solitary: number;
    conceptual: number;
    practical: number;
    empathetic: number;
    logical: number;
    organized: number;
    flexible: number;
}

async function getResult(client: Client, args: GetResultArgs): Promise<GetResultRow | null> {
    const result = await client.query({
        text: getResultQuery,
        values: [args.userId],
        rowMode: "array"
    });
    if (result.rows.length !== 1) {
        return {
            userId: '',
            fullName: '',
            finalResult: '',
            personalityRoleName: '',
            cluster: '',
            outgoing: 0,
            solitary: 0,
            conceptual:0,
            practical: 0,
            empathetic: 0,
            logical: 0,
            organized: 0,
            flexible: 0
        };
    }
    const row = result.rows[0];
    return {
        userId: row[0],
        fullName: row[1],
        finalResult: row[2],
        personalityRoleName: row[3],
        cluster: row[4],
        outgoing: row[5],
        solitary: row[6],
        conceptual: row[7],
        practical: row[8],
        empathetic: row[9],
        logical: row[10],
        organized: row[11],
        flexible: row[12]
    };
}
// -------------------------------------------------------------------------------end of section for GetResult

// -------------------------------------------------------------------------------section for Submit start 
const submitQuery = `-- name: Submit :one
INSERT INTO talent_mapping.user_submissions (
    user_id, respon_1, respon_2, respon_3, respon_4, respon_5, respon_6, respon_7, respon_8, respon_9, respon_10, 
    respon_11, respon_12, respon_13, respon_14, respon_15, respon_16, respon_17, respon_18, respon_19, respon_20, 
    respon_21, respon_22, respon_23, respon_24, respon_25, respon_26, respon_27, respon_28, full_name
) VALUES 
(
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30
) RETURNING user_id`;



export class SubmitArgs {
    @ApiProperty({ description: 'The ID of the user' })
    userId: string;

    @ApiProperty({ description: 'Response 1' })
    respon_1: string;

    @ApiProperty({ description: 'Response 2' })
    respon_2: string;

    @ApiProperty({ description: 'Response 3' })
    respon_3: string;

    @ApiProperty({ description: 'Response 4' })
    respon_4: string;

    @ApiProperty({ description: 'Response 5' })
    respon_5: string;

    @ApiProperty({ description: 'Response 6' })
    respon_6: string;

    @ApiProperty({ description: 'Response 7' })
    respon_7: string;

    @ApiProperty({ description: 'Response 8' })
    respon_8: string;

    @ApiProperty({ description: 'Response 9' })
    respon_9: string;

    @ApiProperty({ description: 'Response 10' })
    respon_10: string;

    @ApiProperty({ description: 'Response 11' })
    respon_11: string;

    @ApiProperty({ description: 'Response 12' })
    respon_12: string;

    @ApiProperty({ description: 'Response 13' })
    respon_13: string;

    @ApiProperty({ description: 'Response 14' })
    respon_14: string;

    @ApiProperty({ description: 'Response 15' })
    respon_15: string;

    @ApiProperty({ description: 'Response 16' })
    respon_16: string;

    @ApiProperty({ description: 'Response 17' })
    respon_17: string;

    @ApiProperty({ description: 'Response 18' })
    respon_18: string;

    @ApiProperty({ description: 'Response 19' })
    respon_19: string;

    @ApiProperty({ description: 'Response 20' })
    respon_20: string;

    @ApiProperty({ description: 'Response 21' })
    respon_21: string;

    @ApiProperty({ description: 'Response 22' })
    respon_22: string;

    @ApiProperty({ description: 'Response 23' })
    respon_23: string;

    @ApiProperty({ description: 'Response 24' })
    respon_24: string;

    @ApiProperty({ description: 'Response 25' })
    respon_25: string;

    @ApiProperty({ description: 'Response 26' })
    respon_26: string;

    @ApiProperty({ description: 'Response 27' })
    respon_27: string;

    @ApiProperty({ description: 'Response 28' })
    respon_28: string;

    @ApiProperty({ description: 'Full name of the user' })
    fullName: string;
}

export interface SubmitRow {
    userId: string;
}

async function submit(client: Client, args: SubmitArgs): Promise<SubmitRow | null> {

    const result = await client.query({
        text: submitQuery,
        values: [
          args.userId, args.respon_1, args.respon_2, args.respon_3, args.respon_4, 
          args.respon_5, args.respon_6, args.respon_7, args.respon_8, args.respon_9, args.respon_10, 
          args.respon_11, args.respon_12, args.respon_13, args.respon_14, args.respon_15, args.respon_16, 
          args.respon_17, args.respon_18, args.respon_19, args.respon_20, args.respon_21, args.respon_22,
          args.respon_23, args.respon_24, args.respon_25, args.respon_26, args.respon_27, args.respon_28, 
          args.fullName
        ],
        rowMode: "array"
    });
    if (result.rows.length !== 1) {
        return null;
    }
    const row = result.rows[0];
    return {
        userId: row[0]
    };
}
// end of section for Submit

